authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('shop/', views.ShopNow.as_view(), name='shop-now'),
    path('create-book/', views.CreateBook.as_view(), name='create-book'),
    path('detail-view/<slug:slug>/', views.ViewProductDetail.as_view(), name='detail-view'),
    path('create-publisher/', views.CreatePublisher.as_view(), name='create-publisher'),
    path('create-genre/', views.CreateGenre.as_view(), name='create-genre'),
    path('delete-book/<slug:slug>/', views.DeleteBook.as_view(), name='delete-book'),
    path('update-book/<slug:slug>/', views.UpdateBook.as_view(), name='update-book'),

    path('search-book/', views.SearchBook.as_view(), name='search-book'),

    path('filter/', views.FilterBook.as_view(), name='filter'),
    path('rating/<slug:slug>/', views.rating, name='rating'),
    path('filter-by-price/', views.FilterBookByPrice.as_view(), name='filter-by-price'),
    path('filter-by-author/', views.FilterBookByAuthor.as_view(), name='filter-by-author'),
    path('add-review/<slug:slug>/', views.AddReviewComment.as_view(), name='add-review'),
]

customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('account/', views.AccountView.as_view(), name='account'),
    path('address/', views.address, name='address'),
    path('update-profile/<int:pk>/', views.UpdateProfile.as_view(), name='update_profile'),
    path('update-avatar/', views.update_avatar, name='update_avatar'),
    path('register-seller/', views.RegisterSellerView.as_view(), name='register_seller'),
    path('shop/<str:shop_name>/', views.SellerView.as_view(), name='shop'),
    path('map/', views.map, name='map'),
]

djangoProject_books/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('myadmin/', admin.site.urls),
                  path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
                  path('author/', include('author.urls')),
                  # path('publisher/', include('publisher.urls')),
                  path('book/', include('book.urls')),
                  path('seller/', include('customer.urls')),
                  path('cart/', include('cart.urls')),
                  path('wishlist/', include('wishlist.urls')),
                  path('order/', include('order.urls')),
                  path('authentication/', include('authentication.urls')),
                  path('myadmin-management/', include('myadmin.urls')),
                  path('', include('index.urls')),
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.Index.as_view(), name='index')
]

order/urls.py
from django.urls import path
from . import views

app_name='order'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create-order/', views.create_order, name='create_order'),
    path('history-order-view/', views.OrderHistoryView.as_view(), name='history_order'),
    path('detail-order/<int:order_id>/', views.order_detail, name='order_detail'),
]

wishlist/urls.py
from django.urls import path

from . import views

app_name = 'wishlist'

urlpatterns = [
    path('my-wishlist/', views.WishlistView.as_view(), name='my-wishlist'),
    path('add-to-wishlist/', views.AddToWishList.as_view(), name='add-to-wishlist'),
    path('remove-from-wishlist/<slug:slug>/', views.remove_from_wishlist, name='remove-from-wishlist'),
]

customer/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    purchased_books = models.ManyToManyField('book.Book', blank=True)
    img_profile = models.ImageField(upload_to='customer_images', blank=True, null=True)

    def __str__(self):
        return self.user.username


class Seller(models.Model):
    customer = models.OneToOneField(Customer, on_delete=models.CASCADE, null=True, blank=True)
    banner = models.ImageField(upload_to='seller_banner', blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    rating = models.FloatField(default=0)
    shop_name = models.CharField(max_length=100)
    # earnings = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    revenue = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return self.shop_name

    def get_avg_rating(self):
        return round(self.rating, 1)

    def get_total_products(self):
        return self.books.count()

    def calculate_revenue(self):
        revenue = 0
        for book in self.books.all():
            # revenue += book.sale_set.aggregate(models.Sum('quantity'))['quantity__sum'] * book.price
            quantity_sum = book.sale_set.aggregate(models.Sum('quantity'))['quantity__sum']
            if quantity_sum is None:
                quantity_sum = 0
            revenue += quantity_sum * book.price
        self.revenue = revenue
        self.save() 

        return revenue

customer/forms.py
from django import forms

from customer.models import Seller


class RegisterSellerForm(forms.ModelForm):
    class Meta:
        model = Seller
        fields = ['shop_name', 'description', 'banner']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3})
        }

customer/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages

from customer.forms import RegisterSellerForm
from customer.models import Customer, Seller


# Create your views here.
class AccountView(generic.TemplateView):
    template_name = 'customer/account.html'


class UpdateProfile(generic.UpdateView):
    template_name = 'customer/update_profile.html'
    model = Customer
    fields = ['address', 'phone', 'img_profile']

    success_url = reverse_lazy('customer:account')

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, "Profile updated successfully")
        return super().form_valid(form)

    def form_invalid(self, form):
        response = super().form_invalid(form)
        response.status_code = 400
        messages.error(self.request, "There was an error in the form")
        return response


def update_avatar(request):
    customer = request.user.customer
    if request.method == 'POST':
        customer.img_profile = request.FILES['avatar']
        customer.save()
        messages.success(request, "Avatar updated successfully")
    return render(request, 'customer/account.html')


def address(request):
    customer = request.user.customer
    if request.method == "POST":
        address = request.POST['address']
        customer.address = address
        customer.save()
    address_customer = customer.address
    return render(request, 'customer/address.html', {'address': address_customer})


class RegisterSellerView(generic.FormView):
    template_name = 'customer/register_seller.html'
    form_class = RegisterSellerForm
    success_url = reverse_lazy('index:index')

    def form_valid(self, form):
        # This form called when valid form data has been posted.
        seller = form.save(commit=False)
        seller.customer = self.request.user.customer
        seller.save()

        return super().form_valid(form)


class SellerView(generic.DetailView):
    """
    A class based view to display the shop of a seller.
    """
    template_name = 'customer/shop.html'
    model = Seller
    context_object_name = 'seller'
    slug_field = 'shop_name'
    slug_url_kwarg = 'shop_name'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = self.object.books.all()
        if len(context['books']) == 0:
            context['empty'] = True
        return context

    def get_object(self, queryset=None):
        return Seller.objects.get(shop_name=self.kwargs['shop_name'])


def map(request):
    return render(request, 'customer/map.html')

customer/templates/customer/account.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    My Account
{% endblock %}



{% block content %}

    <!-- for messages -->
    <div class="container mt-2">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close btn-close" data-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div class="container mt-5">

        <div class="row">
            <div class="col-sm-3 col-md-2 col-lg-2 col-xl-2 text-start">
                <hr/>
                <a href="{% url 'index:index' %}">Dashboard</a>
                <hr/>
                <a href="{% url 'order:history_order' %}">Orders</a>
                <hr/>
                <a href="{% url 'customer:address' %}">Addresses</a>
                <hr/>
                <a href="{% url 'wishlist:my-wishlist' %}">Wishlist</a>
                <hr/>
                <a href="#">Logout</a>
                <hr/>
            </div>
            <div class="col text-start">
                <p>Hello <strong>{{ request.user.username }}</strong> (not <strong>{{ request.user.username }}</strong>?
                    <a href="{% url 'authentication:logout' %}">Log out</a>)</p>
                <p>From your account dashboard you can view your <a
                        href="https://demo2.pavothemes.com/bookory/my-account/orders/">recent orders</a>, manage your <a
                        href="https://demo2.pavothemes.com/bookory/my-account/edit-address/">shipping and billing
                    addresses</a>, and <a href="https://demo2.pavothemes.com/bookory/my-account/edit-account/">edit your
                    password and account details</a>.</p>
                <p><strong>Become a Vendor</strong><br/>Vendors can sell products and manage a store with a vendor
                    dashboard.</p>
                {% if user.customer.img_profile %}
                {% else %}
                    <div>
                        You haven't set your avatar image yet. You can change it.
                        <form action="{% url 'customer:update_avatar' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="file" name="avatar" id="avatar">
                            <input type="submit" value="Upload" class="btn btn-primary btn-sm">
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

customer/templates/customer/address.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    My Address
{% endblock %}



{% block content %}

    <!-- for messages -->
    <div class="container mt-2">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close btn-close" data-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div class="container mt-5">

        <div class="row">
            <div class="col-sm-3 col-md-2 col-lg-2 col-xl-2 text-start">
                <hr/>
                <a href="{% url 'index:index' %}">Dashboard</a>
                <hr/>
                <a href="{% url 'order:history_order' %}">Orders</a>
                <hr/>
                <a href="#">Addresses</a>
                <hr/>
                <a href="{% url 'wishlist:my-wishlist' %}">Wishlist</a>
                <hr/>
                <a href="#">Logout</a>
                <hr/>
            </div>
            <div class="col text-start">
                {% if user.customer.address %}

                    <p>Your address: <span class="fw-bold">{{ address }}</span></p>
                {% else %}
                    You haven't set your address yet:
                    <form action="" method="post">
                    {% csrf_token %}
                        <label for="address">
                            <input type="text" name="address" placeholder="Your address">
                            <input type="submit" value="Upload" class="btn btn-primary btn-sm">

                        </label>
                    </form>
                {% endif %}


            </div>
        </div>
    </div>

{% endblock %}

customer/templates/customer/map.html
{% extends 'base.html' %}
{% block title %}
    Map
{% endblock %}
{% block content %}

    <section class="text-center m-4">
        <h3 class="mb-5">Contact us</h3>
        <div class="row">
            <div class="col-lg-5">
                <iframe
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12094.57348593182!2d-74.00599512526003!3d40.72586666928451!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c2598f988156a9%3A0xd54629bdf9d61d68!2sBroadway-Lafayette%20St!5e0!3m2!1spl!2spl!4v1624523797308!5m2!1spl!2spl"
                        class="h-100 w-100" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            </div>

            <div class="col-lg-6">
                <form>
                    <div class="row">
                        <div class="col-md-9">
                            <div class="row mb-4">
                                <div class="col-md-6 mb-4 mb-md-0">
                                    <div class="form-outline">
                                        <input type="text" id="form3Example1" class="form-control"/>
                                        <label class="form-label" for="form3Example1">First name</label>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-outline">
                                        <input type="email" id="form3Example2" class="form-control"/>
                                        <label class="form-label" for="form3Example2">Email Address</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-outline mb-4">
                                <input type="text" id="form3Example3" class="form-control"/>
                                <label class="form-label" for="form3Example3">Subject</label>
                            </div>
                            <div class="form-outline mb-4">
                                <textarea class="form-control" id="form4Example3" rows="4"></textarea>
                                <label class="form-label" for="form4Example3">Message</label>
                            </div>
                            <div class="text-center text-md-start">
                                <button type="submit" class="btn btn-primary mb-5 mb-md-0">
                                    Send
                                </button>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <ul class="list-unstyled">
                                <li>
                                    <i class="fas fa-map-marker-alt fa-2x text-primary"></i>
                                    <p><small>New York, NY 10012, USA</small></p>
                                </li>
                                <li>
                                    <i class="fas fa-phone fa-2x text-primary"></i>
                                    <p><small>+ 01 234 567 89</small></p>
                                </li>
                                <li>
                                    <i class="fas fa-envelope fa-2x text-primary"></i>
                                    <p><small>contact@gmail.com</small></p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </form>

            </div>
        </div>


    </section>
{% endblock %}

customer/templates/customer/register_seller.html
{% extends 'base.html' %}


{% block title %}
    Register Seller Form
{% endblock %}


{% block content %}




    <div class="container mt-5 text-start">
    <h1 class="text-black mt-5 text-center">Register to become a seller</h1>
    <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {% for field in form %}
                <div class="">
                    <div><label for="{{ field.id_for_label }}" class="text-dark">{{ field.label }}: </label></div>
                    {{ field }}
                </div>
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
            {% endfor %}
            <input type="submit" class="btn btn-info mt-2" value="Create"/>
        </form>
    </div>


{% endblock %}

customer/templates/customer/shop.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ seller.shop_name }}
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'seller/Bootstrap-Cards-v2.css' %}">
    <link rel="stylesheet" href="{% static 'seller/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
{% endblock %}

{% block content %}




    <div class="container-fluid card bg-dark text-white"><img class="card-img" alt="banner image"
                                                              src="{{ seller.banner.url }}">
        <div class="card-img-overlay" style="background-color: rgba(0, 0, 0, 0.5)">
            <h1>{{ seller.shop_name }}</h1>
            <p class="card-text"><span style="background-color: initial;">{{ seller.description }}</span></p>
        </div>
    </div>
    <div class="container">
        <div class="bootstrap_cards2">
            <div class="container py-5">
                <!-- For Demo Purpose-->
                <header class="text-center mb-5">
                    <h1 class="display-4 font-weight-bold text-black">{{ seller.shop_name }}</h1>
                </header>


                <!-- First Row [Prosucts]-->
                <h2 class="font-weight-bold mb-2">From the Shop</h2>
                <p class="font-italic text-muted mb-4">{{ seller.description|truncatewords:20 }}</p>

                <div class="row pb-5 mb-4">
                    {% if empty %}
                        <p class="text-big fst-italic">The shop has no added any books to their bookshelf yet.</p>
                    {% endif %}
                    {% for book in books %}

                        <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
                            <!-- Card-->
                            <div class="card rounded shadow-sm border-0 text-start">
                                <div class="card-body p-4"><img
                                        src="{{ book.image.url }}"
                                        alt="" class="img-fluid d-block mx-auto mb-3">
                                    <h5><a href="{% url 'book:detail-view' book.slug %}"
                                           class="text-dark text-decoration-none">{{ book.title }}</a></h5>
                                    <p class="small text-muted font-italic">{{ book.description|safe|truncatewords:10 }}</p>
                                    <ul class="list-inline small">
                                        {% for i in "12345"|make_list %}
                                            {% if i|add:0 <= book.get_avg_rating %}
                                                <!-- Filled star -->
                                                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em"
                                                     fill="currentColor"
                                                     viewBox="0 0 16 16" class="bi bi-star-fill"
                                                     style="color: var(--bs-yellow);">
                                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                                                </svg>
                                            {% else %}
                                                <!-- Empty star -->
                                                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em"
                                                     fill="currentColor"
                                                     viewBox="0 0 16 16" class="bi bi-star">
                                                    <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.329-.314.158-.888-.283-.95l-4.898-.696L8.465.792c-.197-.39-.73-.39-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.522 3.356-.83 4.73zm4.905-2.767l-3.686 1.894.694-3.957-2.83-2.68 3.924-.57L7.77 1.71l1.76 3.717 3.924.57-2.83 2.68.694 3.957-3.686-1.894z"></path>
                                                </svg>

                                            {% endif %}
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    {% endfor %}


                </div>


            </div>
        </div>
    </div>


{% endblock %}

customer/templates/customer/update_profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
    Update Profile
{% endblock %}

{% block content %}

    <!-- for messages -->
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close btn-close" data-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>




    <div class="container mt-5 text-start">
        <h1 class="text-black mt-5 text-center">Form update profile</h1>
        <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {% for field in form %}
                <div class="">
                    <div><label for="{{ field.id_for_label }}" class="text-dark">{{ field.label }}: </label></div>
                    {{ field }}
                </div>
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
            {% endfor %}
            <input type="submit" class="btn btn-info mt-2" value="Update"/>
        </form>
    </div>

    <hr>


{% endblock %}