book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('shop/', views.ShopNow.as_view(), name='shop-now'),
    path('create-book/', views.CreateBook.as_view(), name='create-book'),
    path('detail-view/<slug:slug>/', views.ViewProductDetail.as_view(), name='detail-view'),
    path('create-publisher/', views.CreatePublisher.as_view(), name='create-publisher'),
    path('create-genre/', views.CreateGenre.as_view(), name='create-genre'),
    path('delete-book/<slug:slug>/', views.DeleteBook.as_view(), name='delete-book'),
    path('update-book/<slug:slug>/', views.UpdateBook.as_view(), name='update-book'),

    path('search-book/', views.SearchBook.as_view(), name='search-book'),

    path('filter/', views.FilterBook.as_view(), name='filter'),
    path('rating/<slug:slug>/', views.rating, name='rating'),
    path('filter-by-price/', views.FilterBookByPrice.as_view(), name='filter-by-price'),
    path('filter-by-author/', views.FilterBookByAuthor.as_view(), name='filter-by-author'),
    path('add-review/<slug:slug>/', views.AddReviewComment.as_view(), name='add-review'),
]

customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('account/', views.AccountView.as_view(), name='account'),
    path('address/', views.address, name='address'),
    path('update-profile/<int:pk>/', views.UpdateProfile.as_view(), name='update_profile'),
    path('update-avatar/', views.update_avatar, name='update_avatar'),
    path('register-seller/', views.RegisterSellerView.as_view(), name='register_seller'),
    path('shop/<str:shop_name>/', views.SellerView.as_view(), name='shop'),
    path('map/', views.map, name='map'),
]

djangoProject_books/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('myadmin/', admin.site.urls),
                  path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
                  path('author/', include('author.urls')),
                  # path('publisher/', include('publisher.urls')),
                  path('book/', include('book.urls')),
                  path('seller/', include('customer.urls')),
                  path('cart/', include('cart.urls')),
                  path('wishlist/', include('wishlist.urls')),
                  path('order/', include('order.urls')),
                  path('authentication/', include('authentication.urls')),
                  path('myadmin-management/', include('myadmin.urls')),
                  path('', include('index.urls')),
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.Index.as_view(), name='index')
]

order/urls.py
from django.urls import path
from . import views

app_name='order'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create-order/', views.create_order, name='create_order'),
    path('history-order-view/', views.OrderHistoryView.as_view(), name='history_order'),
    path('detail-order/<int:order_id>/', views.order_detail, name='order_detail'),
]

wishlist/urls.py
from django.urls import path

from . import views

app_name = 'wishlist'

urlpatterns = [
    path('my-wishlist/', views.WishlistView.as_view(), name='my-wishlist'),
    path('add-to-wishlist/', views.AddToWishList.as_view(), name='add-to-wishlist'),
    path('remove-from-wishlist/<slug:slug>/', views.remove_from_wishlist, name='remove-from-wishlist'),
]

order/models.py
from django.db import models


# Create your models here.

class Order(models.Model):
    customer = models.ForeignKey('customer.Customer', on_delete=models.CASCADE, null=True)
    books = models.ManyToManyField('book.Book', blank=True, through='OrderBook')
    date = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'Order {self.id}'

    def get_shop_name(self):
        return self.customer.seller.shop_name


class OrderBook(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    book = models.ForeignKey('book.Book', on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return self.book.title

order/views.py
from django.db.models import F, Sum
# Create your views here.
from django.shortcuts import render
from django.views import generic
from book.models import Sale, Book

from .models import Order, OrderBook


# Create your views here.


class Index(generic.View):
    def get(self, request):
        customer = request.user.customer
        order = Order.objects.filter(customer=customer).last()
        if order:
            return render(request, 'order/my_order.html', {'order': order})
        else:
            return render(request, 'order/my_order.html')


# class OrderDetail(generic.DetailView):
#     model = Order
#     template_name = 'order/detail.html'
#     context_object_name = 'order'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['order_books'] = OrderBook.objects.filter(order=self.object)
#
#         return context
#
#
def order_detail(request, order_id):
    order = Order.objects.get(pk=order_id)
    order_books = order.orderbook_set.all()
    return render(request, 'order/detail.html', {'order': order, 'order_books': order_books})


def create_order(request):
    """
    This view creates an order from the cart
    """
    customer = request.user.customer
    cart = request.user.cart

    # Save all the books from the cart to the order
    total = cart.cartbook_set.aggregate(total=Sum(F('quantity') * F('book__price')))['total']
    total = round(total, 2)
    order = Order.objects.create(customer=customer, total=total)

    for cart_book in cart.cartbook_set.all():
        OrderBook.objects.create(order=order, book=cart_book.book, quantity=cart_book.quantity)

        book = cart_book.book
        sale = Sale.objects.create(book=book, quantity=cart_book.quantity)
        sale.save()

        cart_book.delete()

    return render(request, 'order/my_order.html', {'order': order})


class OrderHistoryView(generic.ListView):
    template_name = 'order/history.html'
    context_object_name = 'orders'

    model = Order

    def get_queryset(self):
        return Order.objects.filter(customer=self.request.user.customer)

order/templates/order/detail.html
{% extends 'base.html' %}
{% block title %}
    Order Detail {{ order.id }}
{% endblock %}


{% block content %}
    <h1>Order Detail</h1>
    <p>Order ID: {{ order.id }}</p>
    <p>Order Date: {{ order.date }}</p>
{#    <p>Order Status: {{ order.status }}</p>#}
    <p>Order Total: {{ order.total }}</p>
    <p>Order Items:</p>
    <ul>
        {% for orderbook in order_books %}
            <li > {{ orderbook.book.title }}</li>
        {% endfor %}
    </ul>
{% endblock %}

order/templates/order/history.html
{% extends "base.html" %}


{% block title %}
    Order
{% endblock title %}

{% block link %}


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock link %}

{% block content %}
    <style>
        @import url('https://fonts.googleapis.com/css?family=Assistant');


        .cell-1 {
            border-collapse: separate;
            border-spacing: 0 4em;
            background: #fff;
            border-bottom: 5px solid transparent;
            /*background-color: gold;*/
            background-clip: padding-box;
        }

        thead {
            background: #dddcdc;
        }

        .toggle-btn {
            width: 40px;
            height: 21px;
            background: grey;
            border-radius: 50px;
            padding: 3px;
            cursor: pointer;
            -webkit-transition: all 0.3s 0.1s ease-in-out;
            -moz-transition: all 0.3s 0.1s ease-in-out;
            -o-transition: all 0.3s 0.1s ease-in-out;
            transition: all 0.3s 0.1s ease-in-out;
        }

        .toggle-btn > .inner-circle {
            width: 15px;
            height: 15px;
            background: #fff;
            border-radius: 50%;
            -webkit-transition: all 0.3s 0.1s ease-in-out;
            -moz-transition: all 0.3s 0.1s ease-in-out;
            -o-transition: all 0.3s 0.1s ease-in-out;
            transition: all 0.3s 0.1s ease-in-out;
        }

        .toggle-btn.active {
            background: blue !important;
        }

        .toggle-btn.active > .inner-circle {
            margin-left: 19px;
        }
    </style>

    <div class="container mt-5">

        <div class="row">
            <div class="col-sm-3 col-md-2 col-lg-2 col-xl-2 text-start">
                <hr/>
                <a href="{% url 'index:index' %}">Dashboard</a>
                <hr/>
                <a href="{% url 'order:history_order' %}">Orders</a>
                <hr/>
                <a href="#">Addresses</a>
                <hr/>
                <a href="{% url 'wishlist:my-wishlist' %}">Wishlist</a>
                <hr/>
                <a href="#">Logout</a>
                <hr/>
            </div>
            <div class="col text-start">

                <div class="container mt-5 border border-dark">
                    <div class="d-flex justify-content-center row">
                        <div class="col-md-10">
                            <div class="rounded">
                                <div class="table-responsive table-borderless">
                                    <table class="table">
                                        <thead>
                                        <tr>

                                            <th>Order #</th>
                                            <th>Company name</th>
                                            <th>status</th>
                                            <th>Total</th>
                                            <th>Created</th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        <tbody class="table-body">
                                        {% for order in orders %}

                                            <tr class="cell-1">

                                                <td><a href="{% url 'order:order_detail' order.id %}">{{ order.id }}</a>
                                                </td>
                                                <td>
                                                    {% for book in order.books.all %}
                                                        <a class="text-decoration-none " href="{% url 'customer:shop' book.seller.shop_name %}">{{ book.seller.shop_name }}, </a>
                                                    {% endfor %}

                                                </td>
                                                <td><span class="badge badge-success">Fullfilled</span></td>
                                                <td>${{ order.total }}</td>
                                                <td>{{ order.date }}</td>
                                                <td><i class="fa fa-ellipsis-h text-black-50"></i></td>
                                            </tr>
                                        {% endfor %}


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {

            $('.toggle-btn').click(function () {
                $(this).toggleClass('active').siblings().removeClass('active');
            });

        });
    </script>

{% endblock content %}

{% block link-scripts %}

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>


{% endblock link-scripts %}

order/templates/order/my_order.html
{% extends "base.html" %}


{% block title %}
    Order
{% endblock title %}


{% block content %}
    <style>
        .gradient-custom {
            /* fallback for old browsers */
            background: #cd9cf2;

            /* Chrome 10-25, Safari 5.1-6 */
            background: -webkit-linear-gradient(to top left, rgb(255, 255, 255), rgba(246, 243, 255, 1));

            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            background: linear-gradient(to top left, rgba(205, 156, 242, 1), rgba(246, 243, 255, 1))
        }
    </style>

    <section class="h-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-10 col-xl-8">
                    <div class="card" style="border-radius: 10px;">
                        <div class="card-header px-4 py-5">
                            <h5 class="text-muted mb-0">Thanks for your Order, <span
                                    style="color: #a8729a;">{{ user.username }}</span>!</h5>
                        </div>
                        <div class="card-body p-4">
                            <div class="d-flex justify-content-between align-items-center mb-4">
                                <p class="lead fw-normal mb-0" style="color: #a8729a;">Receipt</p>
                                <p class="small text-muted mb-0">Receipt Voucher : 1KAU9-84UIL</p>
                            </div>

                            {% for order_book in order.orderbook_set.all %}
                                <div class="card shadow-0 border mb-4">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-md-2">
                                                <img src="{{ order_book.book.image.url }}"
                                                     class="img-fluid" alt="Phone">
                                            </div>
                                            <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                                <p class=" mb-0">{{ order_book.book.title }}</p>
                                            </div>

                                            <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                                <p class="text-muted mb-0 small">Quantity: {{ order_book.quantity }}</p>
                                            </div>
                                            <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                                <p class="text-muted mb-0 small">${{ order_book.book.price }}</p>
                                            </div>
                                        </div>
                                        <hr class="mb-4" style="background-color: #e0e0e0; opacity: 1;">
                                        <div class="row d-flex align-items-center">
                                            <div class="col-md-2">
                                                <p class="text-muted mb-0 small">Track Order</p>
                                            </div>
                                            <div class="col-md-10">
                                                <div class="progress" style="height: 6px; border-radius: 16px;">
                                                    <div class="progress-bar" role="progressbar"
                                                         style="width: 65%; border-radius: 16px; background-color: #a8729a;"
                                                         aria-valuenow="65"
                                                         aria-valuemin="0" aria-valuemax="100"></div>
                                                </div>
                                                <div class="d-flex justify-content-around mb-1">
                                                    <p class="text-muted mt-1 mb-0 small ms-xl-5">Out for delivary</p>
                                                    <p class="text-muted mt-1 mb-0 small ms-xl-5">Delivered</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            {% endfor %}
                            <div class="d-flex justify-content-between pt-2">
                                <p class="fw-bold mb-0">Order Details</p>
                                <p class="text-muted mb-0"><span class="fw-bold me-4">Total</span> ${{ order.total }}</p>
                            </div>

                            <div class="d-flex justify-content-between pt-2">
                                <p class="text-muted mb-0">Invoice Number : 788152</p>
                                <p class="text-muted mb-0"><span class="fw-bold me-4">Discount</span> $19.00</p>
                            </div>

                            <div class="d-flex justify-content-between">
                                <p class="text-muted mb-0">Invoice Date  {{ order.date }}</p>
                                <p class="text-muted mb-0"><span class="fw-bold me-4">GST 18%</span> 123</p>
                            </div>

                            <div class="d-flex justify-content-between mb-5">
                                <p class="text-muted mb-0">Recepits Voucher : 18KU-62IIK</p>
                                <p class="text-muted mb-0"><span class="fw-bold me-4">Delivery Charges</span> Free</p>
                            </div>
                        </div>
                        <div class="card-footer border-0 px-4 py-5"
                             style="background-color: #a8729a; border-bottom-left-radius: 10px; border-bottom-right-radius: 10px;">
                            <h5 class="d-flex align-items-center justify-content-end text-white text-uppercase mb-0">
                                Total
                                paid: <span class="h2 mb-0 ms-2">${{ order.total }}</span></h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}