book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('shop/', views.ShopNow.as_view(), name='shop-now'),
    path('create-book/', views.CreateBook.as_view(), name='create-book'),
    path('detail-view/<slug:slug>/', views.ViewProductDetail.as_view(), name='detail-view'),
    path('create-publisher/', views.CreatePublisher.as_view(), name='create-publisher'),
    path('create-genre/', views.CreateGenre.as_view(), name='create-genre'),
    path('delete-book/<slug:slug>/', views.DeleteBook.as_view(), name='delete-book'),
    path('update-book/<slug:slug>/', views.UpdateBook.as_view(), name='update-book'),

    path('search-book/', views.SearchBook.as_view(), name='search-book'),

    path('filter/', views.FilterBook.as_view(), name='filter'),
    path('rating/<slug:slug>/', views.rating, name='rating'),
    path('filter-by-price/', views.FilterBookByPrice.as_view(), name='filter-by-price'),
    path('filter-by-author/', views.FilterBookByAuthor.as_view(), name='filter-by-author'),
    path('add-review/<slug:slug>/', views.AddReviewComment.as_view(), name='add-review'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('add-to-cart/', views.AddToCart.as_view(), name='add_to_cart'),
    path('remove-from-cart/', views.RemoveFromCart.as_view(), name='remove_from_cart'),
    path('update_quantity/<int:book_id>/', views.change_quantity, name='update_quantity'),
]

djangoProject_books/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('myadmin/', admin.site.urls),
                  path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
                  path('author/', include('author.urls')),
                  # path('publisher/', include('publisher.urls')),
                  path('book/', include('book.urls')),
                  path('seller/', include('customer.urls')),
                  path('cart/', include('cart.urls')),
                  path('wishlist/', include('wishlist.urls')),
                  path('order/', include('order.urls')),
                  path('authentication/', include('authentication.urls')),
                  path('myadmin-management/', include('myadmin.urls')),
                  path('', include('index.urls')),
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.Index.as_view(), name='index')
]

myadmin/urls.py
from django.urls import path
from . import views

app_name = 'myadmin'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('profile/', views.ProfileVieW.as_view(), name='profile'),
    path('table/', views.TableVieW.as_view(), name='table'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('chart/get-seller/', views.get_sellers, name='get-sellers'),

]

order/urls.py
from django.urls import path
from . import views

app_name='order'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create-order/', views.create_order, name='create_order'),
    path('history-order-view/', views.OrderHistoryView.as_view(), name='history_order'),
    path('detail-order/<int:order_id>/', views.order_detail, name='order_detail'),
]

templates/header.html
{% load static %}
{% load shops_tag %}
<header>

    <div class="container-fluid" style="padding-left: 0px;padding-right: 0px;background: #F65C4E;">
        <div class="row">
            <div class="col-12 col-sm-4 col-md-3 col-lg-3 col-xl-3 d-flex d-lg-flex d-xl-flex justify-content-evenly align-items-center align-items-lg-center align-items-xl-center">
                <h1 class="d-xl-flex align-items-xl-center" style="color: var(--bs-warning);">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                         viewBox="0 0 16 16" class="bi bi-book" style="color: var(--bs-warning);margin-right: 11px;">
                        <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783"></path>
                    </svg>
                    <a href="{% url 'index:index' %}" style="color: white;" class='text-decoration-none'>BOOK</a>
                </h1>
            </div>
            <div class="col-9 col-sm-8 col-md-6 col-lg-6 col-xl-6">
                <form class="search-form" method='get' action='{% url 'book:search-book' %}'>
                    <div class="input-group">
                        <span class="input-group-text">
                            <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30"
                                 viewBox="0 0 50 50">
<path d="M 21 3 C 11.621094 3 4 10.621094 4 20 C 4 29.378906 11.621094 37 21 37 C 24.710938 37 28.140625 35.804688 30.9375 33.78125 L 44.09375 46.90625 L 46.90625 44.09375 L 33.90625 31.0625 C 36.460938 28.085938 38 24.222656 38 20 C 38 10.621094 30.378906 3 21 3 Z M 21 5 C 29.296875 5 36 11.703125 36 20 C 36 28.296875 29.296875 35 21 35 C 12.703125 35 6 28.296875 6 20 C 6 11.703125 12.703125 5 21 5 Z"></path>
</svg>  
                        </span>
                        <input class="form-control" type="text" placeholder="I am looking for.." name='q'>
                        <button class="btn btn-light" type="submit">Search</button>
                    </div>
                </form>
            </div>
            <div class="col-3 col-md-3 col-lg-3 col-xl-3 d-sm-flex d-md-flex d-lg-flex d-xl-flex justify-content-sm-end justify-content-md-end align-items-md-center justify-content-lg-end align-items-lg-center justify-content-xl-end align-items-xl-center">
                {% if user.is_authenticated %}
                    <div class="dropdown" style="margin-right: 10px">


                        <button class="btn dropdown-toggle" aria-expanded="false" data-bs-toggle="dropdown"
                                type="button" style="width: 100px;">
                            {% if user.customer.img_profile %}
                                <img src="{{ user.customer.img_profile.url }}" style="width: 80%;border-radius: 100%;"
                                     alt="{{ user.username }}"/>
                            {% else %}
                                <i class="bi bi-person-fill"
                                   style="color: white; font-size: 27px;margin-right: 10px;"></i>
                            {% endif %}
                        </button>

                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'customer:account' %}">Profile</a>
{#                            <a class="dropdown-item" href="{% url 'book:create-book' %}">Create Book</a>#}
                            <a class="dropdown-item" href="{% url 'customer:update_profile' user.customer.id %}">Update
                                Profile</a>
                            <a class="dropdown-item" href="{% url 'order:index' %}">Order</a>
                            <a class="dropdown-item" href="{% url 'authentication:logout' %}">Logout</a>
                            <a class="dropdown-item" href="{% url 'order:history_order' %}">Order History</a>
                        </div>
                    </div>
                {% else %}
                    <a href="{% url 'authentication:login' %}">
                        <i class="bi bi-person-fill" style="color: white; font-size: 27px;margin-right: 10px;"></i>
                    </a>
                {% endif %}
                <a href="{% url 'wishlist:my-wishlist' %}" class="text-decoration-none" style="margin-right:10px">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="white" viewBox="0 0 16 16"
                         class="bi bi-suit-heart" style="font-size: 27px; color: white">
                        <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"></path>
                    </svg>
                    <span class='badge badge-warning' id='lblCartCount'> {{ user.customer.wishlist_set.count }} </span>

                </a>
                <a href="{% url 'cart:cart' %}" class="text-decoration-none" style="margin-right: 20px">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                         viewBox="0 0 16 16"
                         class="bi bi-cart" style="font-size: 27px; color: white">
                        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"></path>
                    </svg>
                    <span class='badge badge-warning' id='lblCartCount'> {{ user.cart.cartbook_set.count }} </span>
                    <style>
                        .badge {
                            padding-left: 9px;
                            padding-right: 9px;
                            -webkit-border-radius: 9px;
                            -moz-border-radius: 9px;
                            border-radius: 9px;
                        }

                        .label-warning[href],
                        .badge-warning[href] {
                            background-color: #c67605;
                        }

                        #lblCartCount {
                            font-size: 12px;
                            background: white;
                            color: #F65B4E;
                            padding: 0 5px;
                            vertical-align: top;
                            margin-left: -10px;
                        }

                    </style>
            </div>
        </div>
        <nav class="navbar navbar-expand-md bg-body py-3">
            <div class="container"><a class="navbar-brand d-flex align-items-center" href="#"><span
                    class="bs-icon-sm bs-icon-rounded bs-icon-primary d-flex justify-content-center align-items-center me-2 bs-icon"
                    style="background: var(--bs-body-bg);"><svg class="bi bi-pin-map-fill"
                                                                xmlns="http://www.w3.org/2000/svg" width="1em"
                                                                height="1em" fill="currentColor" viewBox="0 0 16 16"
                                                                style="border-color: var(--bs-navbar-active-color);color: var(--bs-navbar-active-color);">
                            <path fill-rule="evenodd"
                                  d="M3.1 11.2a.5.5 0 0 1 .4-.2H6a.5.5 0 0 1 0 1H3.75L1.5 15h13l-2.25-3H10a.5.5 0 0 1 0-1h2.5a.5.5 0 0 1 .4.2l3 4a.5.5 0 0 1-.4.8H.5a.5.5 0 0 1-.4-.8z"></path>
                            <path fill-rule="evenodd"
                                  d="M4 4a4 4 0 1 1 4.5 3.969V13.5a.5.5 0 0 1-1 0V7.97A4 4 0 0 1 4 3.999z"></path>
                        </svg></span><span><a href="{% url 'customer:map' %}"
                                              style="font-size: 13px;">Find a Book Store</a></span></a>
                <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navcol-3"><span
                        class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span>
                </button>
                <div id="navcol-3" class="collapse navbar-collapse">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item"><a class="nav-link active" href="/">Home</a></li>
                    {% if user.customer.seller %}

                        <li class="nav-item"><a class="nav-link" href="{% url 'customer:shop' user.customer.seller.shop_name %}">Your shop</a></li>
                    {% endif %}

                        <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" aria-expanded="false"
                                                         data-bs-toggle="dropdown" href="#">Vendor </a>
                            <div class="dropdown-menu">
                                {% get_sellers as sellers %}
                                {% for seller in sellers %}
                                    <a class="dropdown-item"
                                       href="{% url 'customer:shop' seller.shop_name %}">{{ seller.shop_name }}</a>
                                {% endfor %}

                            </div>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="#">Pages</a></li>
                        {% if user.is_superuser %}

                            <li class="nav-item"><a class="nav-link" href="{% url 'myadmin:index' %}">Admin</a></li>
                        {% endif %}

                        <li class="nav-item"><a class="nav-link" href="#">Contact</a></li>
                        {% if user.is_authenticated %}

                            {% if user.customer.seller %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'book:create-book' %}">Sell
                                    Book</a></li>
                            {% else %}

                                <li class="nav-item">
                                <a class="nav-link active" href="{% url 'customer:register_seller' %}">Register to
                                    become a seller</a>
                            {% endif %}


                        {% endif %}

                    </ul>
                    <button class="btn btn-primary d-xl-flex align-items-xl-center" type="button"
                            style="background: var(--bs-body-bg);border-style: none;">
                        <svg class="bi bi-telephone-fill" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em"
                             fill="currentColor" viewBox="0 0 16 16"
                             style="border-color: var(--bs-navbar-brand-color);color: var(--bs-navbar-brand-color);">
                            <path fill-rule="evenodd"
                                  d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"></path>
                        </svg>
                        <strong><span style="color: rgb(213, 48, 48);">  +1 840 - 841 25 69 </span></strong></button>
                </div>
            </div>
        </nav>

    </div>

</header>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

templates/thumbnail.html
{% load static %}

<section id="thumbnai-top" style="padding-top: 15px;">
    <div class="row d-flex justify-content-evenly">
        <div class="col-md-5 col-lg-6 col-xl-5 col-xxl-4 position-relative"><img class="img-fluid position-relative"
                                                                                 src="{% static 'assets/img/rev_home8.png' %}"/><img
                class="position-absolute" src="{% static 'assets/img/rev_home8_7.png' %}"
                style="transform: translate(142px) translateX(-441px);"/><img class="position-absolute"
                                                                              src="{% static 'assets/img/rev_home8_3.png' %}"
                                                                              style="transform: translate(-465px);"/><img
                class="position-absolute" src="{% static 'assets/img/rev_home8_4.png' %}"
                style="transform: translateX(-222px) translateY(361px);"/></div>
        <div class="col-md-5 col-lg-5 col-xl-5 col-xxl-4 d-flex d-sm-flex d-lg-flex d-xl-flex flex-column align-items-center justify-content-sm-center align-items-sm-center align-items-lg-center align-items-xl-center">
            <h1 class="justify-content-lg-center position-relative"><strong><em><span style="color: rgb(0, 0, 0);">The Best Books of </span></em></strong><br/><strong><em><span
                    style="color: rgb(0, 0, 0);">All Time</span></em></strong><img class="position-absolute"
                                                                                   src="{% static 'assets/img/revslider_vector.png' %}"
                                                                                   style="transform: translateX(-271px) translateY(-5px);"/>
            </h1>
            <span class="text-center fst-italic">
                “The more that you read, the more things you will know. The more that you learn, the more places you'll go.” !
                <br>― Dr. Seuss, I Can Read With My Eyes Shut! 
            </span>
            <style>
                .text-center.fst-italic {
                    font-size: 20px; /* Increase the font size */
                    color: #ff6347; /* Change the text color to tomato */
                    background-color: #f0f8ff; /* Add a light blue background */
                    border: 2px solid #ff6347; /* Add a border */
                    padding: 10px; /* Add some padding */
                    border-radius: 10px; /* Round the corners of the border */
                    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.1); /* Add a subtle shadow */
                }
            </style>
            <button class="btn btn-primary d-xxl-flex justify-content-xxl-center align-items-xxl-center" type="button"
                    style="background: var(--bs-btn-disabled-color);border-radius: 20px;border-style: none;width: 225px;margin-top: 50px;">
                <a href="{% url 'book:shop-now' %}" style="color: rgb(0, 0, 0);">Shop Now</a>
                <svg class="bi bi-arrow-right" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em"
                     fill="currentColor" viewBox="0 0 16 16" style="color: var(--bs-emphasis-color);margin-left: 7px;">
                    <path fill-rule="evenodd"
                          d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8"></path>
                </svg>
            </button>
        </div>
    </div>
    <div class="container py-4 py-xl-5">
        <div class="row gy-4 row-cols-2 row-cols-md-4">
            <div class="col">
                <div class="text-center d-flex flex-column justify-content-center align-items-center py-3">
                    <div class="bs-icon-xl bs-icon-circle bs-icon-primary d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block mb-2 bs-icon lg">
                        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                             viewBox="0 0 16 16" class="bi bi-bell">
                            <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2M8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6"></path>
                        </svg>
                    </div>
                    <div class="px-3">
                        <h2 class="fw-bold mb-0">123+</h2>
                        <p class="mb-0">Erat netus</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="text-center d-flex flex-column justify-content-center align-items-center py-3">
                    <div class="bs-icon-xl bs-icon-circle bs-icon-primary d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block mb-2 bs-icon lg">
                        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                             viewBox="0 0 16 16" class="bi bi-bezier">
                            <path fill-rule="evenodd"
                                  d="M0 10.5A1.5 1.5 0 0 1 1.5 9h1A1.5 1.5 0 0 1 4 10.5v1A1.5 1.5 0 0 1 2.5 13h-1A1.5 1.5 0 0 1 0 11.5zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zm10.5.5A1.5 1.5 0 0 1 13.5 9h1a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1-1.5-1.5zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zM6 4.5A1.5 1.5 0 0 1 7.5 3h1A1.5 1.5 0 0 1 10 4.5v1A1.5 1.5 0 0 1 8.5 7h-1A1.5 1.5 0 0 1 6 5.5zM7.5 4a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5z"></path>
                            <path d="M6 4.5H1.866a1 1 0 1 0 0 1h2.668A6.517 6.517 0 0 0 1.814 9H2.5c.123 0 .244.015.358.043a5.517 5.517 0 0 1 3.185-3.185A1.503 1.503 0 0 1 6 5.5zm3.957 1.358A1.5 1.5 0 0 0 10 5.5v-1h4.134a1 1 0 1 1 0 1h-2.668a6.517 6.517 0 0 1 2.72 3.5H13.5c-.123 0-.243.015-.358.043a5.517 5.517 0 0 0-3.185-3.185z"></path>
                        </svg>
                    </div>
                    <div class="px-3">
                        <h2 class="fw-bold mb-0">45+</h2>
                        <p class="mb-0">Erat netus</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="text-center d-flex flex-column justify-content-center align-items-center py-3">
                    <div class="bs-icon-xl bs-icon-circle bs-icon-primary d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block mb-2 bs-icon lg">
                        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                             viewBox="0 0 16 16" class="bi bi-cup">
                            <path fill-rule="evenodd"
                                  d="M.11 3.187A.5.5 0 0 1 .5 3h13a.5.5 0 0 1 .488.608l-.22.991a3.001 3.001 0 0 1-1.3 5.854l-.132.59A2.5 2.5 0 0 1 9.896 13H4.104a2.5 2.5 0 0 1-2.44-1.958L.012 3.608a.5.5 0 0 1 .098-.42Zm12.574 6.288a2 2 0 0 0 .866-3.899l-.866 3.9ZM1.124 4l1.516 6.825A1.5 1.5 0 0 0 4.104 12h5.792a1.5 1.5 0 0 0 1.464-1.175L12.877 4H1.123Z"></path>
                        </svg>
                    </div>
                    <div class="px-3">
                        <h2 class="fw-bold mb-0">67+</h2>
                        <p class="mb-0">Erat netus</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="text-center d-flex flex-column justify-content-center align-items-center py-3">
                    <div class="bs-icon-xl bs-icon-circle bs-icon-primary d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block mb-2 bs-icon lg">
                        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                             viewBox="0 0 16 16" class="bi bi-cart2">
                            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0"></path>
                        </svg>
                    </div>
                    <div class="px-3">
                        <h2 class="fw-bold mb-0">89</h2>
                        <p class="mb-0">Erat netus</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>