author/urls.py
from django.urls import path
from . import views

app_name = 'author'

urlpatterns = [
    path('create-author/', views.CreateAuthor.as_view(), name='create-author'),
    path('show-detail/<int:pk>/', views.AuthorDetail.as_view(), name='author-detail'),
]

book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('shop/', views.ShopNow.as_view(), name='shop-now'),
    path('create-book/', views.CreateBook.as_view(), name='create-book'),
    path('detail-view/<slug:slug>/', views.ViewProductDetail.as_view(), name='detail-view'),
    path('create-publisher/', views.CreatePublisher.as_view(), name='create-publisher'),
    path('create-genre/', views.CreateGenre.as_view(), name='create-genre'),
    path('delete-book/<slug:slug>/', views.DeleteBook.as_view(), name='delete-book'),
    path('update-book/<slug:slug>/', views.UpdateBook.as_view(), name='update-book'),

    path('search-book/', views.SearchBook.as_view(), name='search-book'),

    path('filter/', views.FilterBook.as_view(), name='filter'),
    path('rating/<slug:slug>/', views.rating, name='rating'),
    path('filter-by-price/', views.FilterBookByPrice.as_view(), name='filter-by-price'),
    path('filter-by-author/', views.FilterBookByAuthor.as_view(), name='filter-by-author'),
    path('add-review/<slug:slug>/', views.AddReviewComment.as_view(), name='add-review'),
]

customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('account/', views.AccountView.as_view(), name='account'),
    path('address/', views.address, name='address'),
    path('update-profile/<int:pk>/', views.UpdateProfile.as_view(), name='update_profile'),
    path('update-avatar/', views.update_avatar, name='update_avatar'),
    path('register-seller/', views.RegisterSellerView.as_view(), name='register_seller'),
    path('shop/<str:shop_name>/', views.SellerView.as_view(), name='shop'),
    path('map/', views.map, name='map'),
]

djangoProject_books/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('myadmin/', admin.site.urls),
                  path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
                  path('author/', include('author.urls')),
                  # path('publisher/', include('publisher.urls')),
                  path('book/', include('book.urls')),
                  path('seller/', include('customer.urls')),
                  path('cart/', include('cart.urls')),
                  path('wishlist/', include('wishlist.urls')),
                  path('order/', include('order.urls')),
                  path('authentication/', include('authentication.urls')),
                  path('myadmin-management/', include('myadmin.urls')),
                  path('', include('index.urls')),
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
import uuid

from django.db import models
from django.utils.text import slugify
from django_ckeditor_5.fields import CKEditor5Field

from customer.models import Seller


# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='book_images')
    author = models.ManyToManyField('author.Author',
                                    blank=True)
    price = models.DecimalField(max_digits=5,
                                decimal_places=2)
    stock = models.IntegerField()
    deal_of_the_week = models.BooleanField(default=False)
    publisher = models.ForeignKey('publisher.Publisher',
                                  on_delete=models.CASCADE),
    description = CKEditor5Field('Text',
                                 config_name='extends')
    genre = models.ManyToManyField('Genre', blank=True)
    slug = models.SlugField(unique=True, default=None)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE,
                               related_name='books', null=True)

    def get_avg_rating(self):
        return self.reviews.aggregate(models.Avg('rating'))['rating__avg'] or 0

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
        if Book.objects.filter(slug=self.slug).exclude(id=self.id).exists():
            self.slug = f"{self.slug}-{uuid.uuid4()}"
            super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Genre(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='reviews')
    rating = models.IntegerField()
    review = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f"{self.book.title} - {self.rating}"


class Sale(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    sale_date = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if self.quantity > self.book.stock:
            raise ValueError('Sale quantity cannot be greater than stock')
        else:
            self.book.stock -= self.quantity
            self.book.save()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.book.title} - {self.quantity} - {self.book.title}"

book/forms.py
from django import forms
from django_ckeditor_5.widgets import CKEditor5Widget

from .models import Book, Genre, Review


class BookForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['description'].required = False

    class Meta:
        model = Book
        exclude = ['slug', 'seller']


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = '__all__'


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'review']

book/views.py
import json

from django.contrib import messages
from django.db.models import Avg, Sum, Max, Min
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.core.cache import cache
from django.core.paginator import Paginator

from author.models import Author
from book.forms import BookForm
from book.models import Book, Genre, Review
from publisher.models import Publisher
from order.models import Order, OrderBook


# Create your views here.


def get_genres():
    genres = cache.get('genres')
    if not genres:
        genres = list(Genre.objects.all())
        cache.set('genres', genres, 60 * 60 * 24)  # cache for 24 hours
    return genres


def get_authors():
    authors = cache.get('authors')
    if not authors:
        authors = list(Author.objects.all())
        cache.set('authors', authors, 60 * 60 * 24)  # cache for 24 hours
    return authors


class Index(generic.View):
    def get(self, request):
        return render(request, 'index/index.html')


class ViewProductDetail(generic.DetailView):
    model = Book
    template_name = 'book/detail.html'
    context_object_name = 'book'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        avg_rating = self.object.reviews.aggregate(Avg('rating'))['rating__avg'] or 0
        context['avg_rating'] = round(avg_rating)
        context['sold_quantity'] = self.object.sale_set.aggregate(Sum('quantity'))['quantity__sum'] or 0
        context['percentage_sold'] = round((context['sold_quantity'] / self.object.stock) * 100)
        return context


class ShopNow(generic.TemplateView):
    template_name = 'book/shop_now_filters.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        books = Book.objects.all()
        # context['books'] = Book.objects.all()
        paginator = Paginator(books, 12)

        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['books'] = page_obj

        context['genres'] = get_genres()
        context['authors'] = get_authors()

        max_price = Book.objects.aggregate(Max('price'))['price__max']
        min_price = Book.objects.aggregate(Min('price'))['price__min']
        context['max_price'] = round(max_price, 2)
        context['min_price'] = round(min_price, 2)

        # book_list = []
        # for book in books:
        #     book.avg_rating = round(book.reviews.aggregate(Avg('rating'))['rating__avg'] or 0)
        #     book_list.append(book)

        # context['books'] = book_list
        return context


class CreateBook(generic.CreateView):
    template_name = 'book/create_book.html'
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('book:shop-now')
    success_message = 'Added Book successfully'

    def form_valid(self, form):
        form.instance.seller = self.request.user.customer.seller
        response = super().form_valid(form)
        messages.success(self.request, self.success_message)
        return response


class CreateGenre(generic.CreateView):
    template_name = 'book/create_genre.html'
    model = Genre
    fields = '__all__'

    success_message = 'Genre created successfully'
    success_url = reverse_lazy('book:create-book')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, self.success_message)
        return response


class CreatePublisher(generic.CreateView):
    template_name = 'book/create_publisher.html'
    model = Publisher
    fields = '__all__'

    success_message = 'Publisher created successfully'

    success_url = reverse_lazy('book:create-book')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, self.success_message)
        return response


class DeleteBook(generic.DeleteView):
    model = Book
    success_url = reverse_lazy('book:shop-now')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Book deleted successfully')
        return super().delete(request, *args, **kwargs)


class UpdateBook(generic.UpdateView):
    template_name = 'book/update_book.html'
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('book:shop-now')
    success_message = 'Book updated successfully'

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, self.success_message)
        return response


class SearchBook(generic.ListView):
    template_name = 'book/search_book.html'
    context_object_name = 'books'
    q = ''

    def get_queryset(self):
        query = self.request.GET.get('q')
        self.q = query
        books = Book.objects.filter(title__icontains=query)
        if len(books) == 0:
            messages.warning(self.request, f'There is no result for this {self.q}')
        return books

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["query"] = self.q
        return context


# Filter by genre
class FilterBook(generic.ListView):
    template_name = 'book/shop_now_filters.html'
    context_object_name = 'books'
    genres = []

    def get_queryset(self):
        genres = self.request.GET.getlist('genres')
        self.genres = genres
        books = Book.objects.filter(genre__name__in=genres)
        return books

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = get_genres()
        context['authors'] = get_authors()
        context['genres_filtered'] = self.genres
        return context


# Filter by price
class FilterBookByPrice(generic.ListView):
    template_name = 'book/shop_now_filters.html'
    context_object_name = 'books'

    def get_queryset(self):
        price = self.request.GET.get('value_price_input')
        books = Book.objects.filter(price__lte=price)

        return books

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = get_genres()
        context['authors'] = get_authors()
        return context


class FilterBookByAuthor(generic.ListView):
    template_name = 'book/shop_now_filters.html'
    context_object_name = 'books'

    def get_queryset(self):
        authors = self.request.GET.getlist('authors')
        print(authors)
        books = Book.objects.filter(author__name__in=authors)
        return books

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = get_genres()
        context['authors'] = get_authors()
        return context


def rating(request, slug):
    if request.user.is_anonymous:
        return redirect('authentication:login')
    book = Book.objects.get(slug=slug)
    data = json.loads(request.body)
    rating_value = data.get('rating')
    book.reviews.update_or_create(user=request.user, defaults={'rating': rating_value})

    return JsonResponse(
        {'status': 'success', 'message': 'Rating added successfully', 'rating_total': book.reviews.all().count()})


class AddReviewComment(generic.View):
    def post(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('authentication:login')
        # If user already purchased the book then only he can review the book
        if OrderBook.objects.filter(order__customer=request.user.customer, book__slug=self.kwargs['slug']).exists():
            book = Book.objects.get(slug=self.kwargs['slug'])
            review = request.POST.get('review')
            rating = request.POST.get('rating')
            book.reviews.update_or_create(user=request.user, defaults={'rating': rating, 'review': review})
            return redirect('book:detail-view', slug=self.kwargs['slug'])
        else:
            messages.error(request, 'You can only review the book after purchasing it')
            return redirect('book:detail-view', slug=self.kwargs['slug'])

        # return redirect('book:detail-view', slug=self.kwargs['slug'])

book/templates/book/comments.html
<div class="row">
            <div class="col-xl-11 mx-auto">
                <div class="card">
                    <div class="card-header">
                        <h3>Community Reviews</h3>
                    </div>
                    <div class="card-body">
                        <ul class="list-group">
                            {% for review in book.reviews.all %}


                                <li class="list-group-item" style="margin-bottom: 6px;">
                                    <div class="d-flex media">
                                        <div></div>
                                        <div class="media-body">
                                            <div class="d-flex media" style="overflow: visible;">
                                                <div>
                                                    {% if review.user.customer.img_profile %}

                                                    <img class="me-3" style="width: 25px;height: 25px;"
                                                         src="{{ review.user.customer.img_profile.url }}"
                                                         alt="{{ review.user.username }}"/>
                                                    {% else %}
                                                        <img class="me-3" style="width: 25px;height: 25px;"
                                                             src="https://i.imgur.com/d2dKtI7.png"
                                                             alt="{{ review.user.username }}"/>
                                                    {% endif %}
                                                </div>
                                                <div class="media-body" style="overflow: visible;">
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <div class="row">
                                                                <div class="col">
                                                                <span
                                                                        class="d-xl-flex align-items-xl-center"
                                                                        style="margin-right: 0px;">
                                                                    {% for i in "12345"|make_list %}
                                                                        {% if i|add:0 <= review.rating %}
                                                                            <!-- Filled star -->
                                                                            <svg
                                                                                    class="bi bi-star-fill"
                                                                                    xmlns="http://www.w3.org/2000/svg"
                                                                                    width="1em"
                                                                                    height="1em" fill="currentColor"
                                                                                    viewBox="0 0 16 16"
                                                                                    style="color: var(--bs-yellow);font-size: 13px;">
                                                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                                                                </svg>  
                                                                        {% else %}
                                                                            <!-- Empty star -->
                                                                            <svg class="bi bi-star"
                                                                                 xmlns="http://www.w3.org/2000/svg"
                                                                                 width="1em" height="1em"
                                                                                 fill="currentColor"
                                                                                 viewBox="0 0 16 16"
                                                                                 style="font-size: 13px;">
                                                                    <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"></path>
                                                                </svg>

                                                                        {% endif %}
                                                                    {% endfor %}


                                                                    </span>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col d-xl-flex justify-content-start align-items-xl-center">
                                                                    <a class="text-decoration-none" href="#"
                                                                       style="margin-right: 21px; margin-top: 4px"><strong><span
                                                                            style="color: rgb(0, 0, 0);">{{ review.user.username }}</span></strong></a><small
                                                                        class="text-muted">{{ review.date }}</small>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col">
                                                                    <p class="small"
                                                                       style="text-align: left;margin-top: 10px;">
                                                                        <span style="color: rgb(68, 68, 68);">{{ review.review }}</span>
                                                                    </p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}


                        </ul>
                        <button class="btn btn-light" data-toggle="modal" data-target="#form"
                                style="margin-left: 601px;margin-top: -9px;" type="button">Add
                            Comment
                        </button>

                        {#      MODAL    #}

                        <div class="modal fade" id="form" tabindex="-1" role="dialog"
                             aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="text-right cross"><i class="fa fa-times mr-2"></i></div>
                                    <div class="card-body text-center">
                                        <img src=" https://i.imgur.com/d2dKtI7.png"
                                             height="100" width="100">
                                        <form class="comment-box text-center" method="post" action="{% url 'book:add-review' book.slug %}">
                                            <h4>Add a comment</h4>
                                            {% csrf_token %}
                                            <div class="rating"><input type="radio" name="rating" value="5"
                                                                       id="5"><label for="5">☆</label> <input
                                                    type="radio" name="rating" value="4" id="4"><label for="4">☆</label>
                                                <input type="radio" name="rating" value="3" id="3"><label
                                                        for="3">☆</label> <input type="radio" name="rating" value="2"
                                                                                 id="2"><label for="2">☆</label> <input
                                                        type="radio" name="rating" value="1" id="1"><label
                                                        for="1">☆</label></div>
                                            <div class="comment-area">
                                                <label>
                                                    <textarea name="review"
                                                            class="form-control"
                                                              placeholder="what is your view?"
                                                              rows="4">

                                                    </textarea>
                                                </label></div>

                                            <div class="text-center mt-4">
                                                <button class="btn btn-success send px-5" type="submit">Comment<i
                                                        class="fa fa-long-arrow-right ml-1"></i></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

book/templates/book/create_book.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
    Create Book Form
{% endblock %}

{% block content %}

    <!-- for messages -->
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close btn-close" data-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>




    <div class="container mt-5 text-start">
     <h1 class="text-black mt-5 text-center">Form to create a book</h1>
    <hr>
        <form method="post" enctype="multipart/form-data" action="{% url 'book:create-book' %}">
            {% csrf_token %}
            {{ form.media }}
            {% for field in form %}
                <div class="">
                    <div><label for="{{ field.id_for_label }}" class="text-dark">{{ field.label }}: </label></div>
                    {{ field }}
                </div>
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
            {% endfor %}
            <input type="submit" class="btn btn-info mt-2" value="Create"/>
        </form>
    </div>

    <hr>

    <div class="container text-start">

        <p>Struggling to find the right <span class="fw-bold">authors</span>? Look no further - <a
                href="{% url 'author:create-author' %}">create
            your
            own here!</a></p>
        <p>Struggling to find the right <span class="fw-bold">genres</span>? Look no further - <a
                href="{% url 'book:create-genre' %}">create your
            own here!</a></p>
        <p>Struggling to find the right <span class="fw-bold">publishers</span>? Look no further - <a
                href="{% url 'book:create-publisher' %}">create
            your own here!</a></p>
    </div>

{% endblock %}

book/templates/book/create_genre.html
{% extends 'base.html' %}

{% block title %}
    Genre Form
{% endblock %}

{% block content %}
    <h1 class="text-center mt-5">Create Genre</h1>
    <div class="container text-start">
        <form method="post">
            {% csrf_token %}
            {{ form.media }}
            {% for field in form %}
                <div class="form-group">
                    <div><label for="{{ field.id_for_label }}" class="text-dark">{{ field.label }}: </label></div>
                    {{ field }}
                </div>
            {% endfor %}
            <input type="submit" class="btn btn-info mt-2" value="Create"/>
        </form>
    </div>

{% endblock %}

book/templates/book/create_publisher.html
{% extends 'base.html' %}

{% block title %}
    Publisher Form
{% endblock %}

{% block content %}
    <h1 class="text-center mt-5">Create Publisher</h1>
    <div class="container mt-5">
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <div><label for="{{ field.id_for_label }}" class="text-dark">{{ field.label }}: </label></div>
                    {{ field }}
                </div>
            {% endfor %}
            <div class="row justify-content-center">
                <input type="submit" class="btn btn-info btn-lg" value="Create"/>
            </div>
        </form>
    </div>

{% endblock %}

book/templates/book/search_book.html
{% extends "base.html" %}

{% block title %}
    Search results for {{ q }}
{% endblock title %}


{% block content %}
    {% if messages %}
        {% for message in messages %}
            <p style="font-size: 30px" class="text-center text-{{ message.tags }}">{{ message }}</p>
        {% endfor %}

    {% endif %}
    <div class='container'>
        <ul>
            {% for book in books %}
                <li class='text-start '>
                    <a href="{% url 'book:detail-view' book.slug %}">{{ book.title }} - {{ book.author.all|join:", " }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

book/templates/book/update_book.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
    Update Book Form
{% endblock %}

{% block content %}


    <h1 class="text-black mt-5 text-center">Form to update a book</h1>
    <hr>


    <div class="container mt-5 text-start">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {% for field in form %}
                <div class="">
                    <div><label for="{{ field.id_for_label }}" class="text-dark">{{ field.label }}: </label></div>
                    {{ field }}
                </div>
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
            {% endfor %}
            <input type="submit" class="btn btn-info mt-2" value="Update"/>
        </form>
    </div>

    <hr>



    <div class="container text-start">

        <p>Struggling to find the right <span class="fw-bold">authors</span>? Look no further - <a
                href="{% url 'author:create-author' %}">create
            your
            own here!</a></p>
        <p>Struggling to find the right <span class="fw-bold">genres</span>? Look no further - <a
                href="{% url 'book:create-genre' %}">create your own here!</a></p>
        <p>Struggling to find the right <span class="fw-bold">publishers</span>? Look no further - <a
                href="{% url 'book:create-publisher' %}">create
            your own here!</a></p>
    </div>

{% endblock %}